import {
  Home, MessageSquare, HelpCircle, Layers, CalendarDays, BookOpen, User, Sparkles, X, LogOut,
  Menu, Search, Plus, FileText, Paperclip, Send, CircleCheck, CircleX, CircleAlert, TriangleAlert,
  ArrowRight, Eye, EyeOff, Mail, Lock, GraduationCap, Building2, MapPin, Download, Upload,
  Trash2, Copy, Bot, Clock, CalendarCheck, CirclePlus, CirclePlay, CalendarX, Book, PenLine,
  ChartBar, Image, Smile, Meh, Frown, Hand, ArrowDown, Star, List, Bell, Calculator, Brain,
  Monitor, Microscope, Globe, SquareCheck, Check, Undo2, Timer, Flame, TrendingUp, Calendar,
  Zap, ChevronDown, ChevronUp, ChevronLeft, ChevronRight,
} from "lucide-react";

const MAP = {
  home: Home,
  chat_bubble: MessageSquare,
  quiz: HelpCircle,
  style: Layers,
  event_note: CalendarDays,
  history_edu: BookOpen,
  account_circle: User,
  person: User,
  logout: LogOut,
  close: X,
  menu: Menu,
  search: Search,
  auto_awesome: Sparkles,
  expand_more: ChevronDown,
  expand_less: ChevronUp,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  timer: Timer,
  local_fire_department: Flame,
  trending_up: TrendingUp,
  event: Calendar,
  calendar_today: CalendarDays,
  calendar_month: Calendar,
  bolt: Zap,
  add: Plus,
  add_card: Plus,
  description: FileText,
  picture_as_pdf: FileText,
  notes: FileText,
  attach_file: Paperclip,
  send: Send,
  check_circle: CircleCheck,
  cancel: CircleX,
  error: CircleAlert,
  error_outline: CircleAlert,
  warning: TriangleAlert,
  arrow_forward: ArrowRight,
  visibility: Eye,
  visibility_off: EyeOff,
  mail: Mail,
  lock: Lock,
  school: GraduationCap,
  corporate_fare: Building2,
  location_on: MapPin,
  cloud_download: Download,
  cloud_upload: Upload,
  delete: Trash2,
  delete_forever: Trash2,
  content_copy: Copy,
  robot_2: Bot,
  schedule: Clock,
  pending: Clock,
  event_available: CalendarCheck,
  add_circle: CirclePlus,
  play_circle: CirclePlay,
  event_busy: CalendarX,
  book: Book,
  menu_book: BookOpen,
  edit_note: PenLine,
  leaderboard: ChartBar,
  image: Image,
  sentiment_very_satisfied: Smile,
  sentiment_neutral: Meh,
  sentiment_very_dissatisfied: Frown,
  touch_app: Hand,
  low_priority: ArrowDown,
  celebration: Star,
  list: List,
  notifications: Bell,
  science: BookOpen,
  calculate: Calculator,
  psychology: Brain,
  computer: Monitor,
  biotech: Microscope,
  translate: Globe,
  task_alt: SquareCheck,
  check: Check,
  undo: Undo2,
  check_circle_outline: CircleCheck,
};

export default function Icon({ name, size = 20, style, className }) {
  const LucideIcon = MAP[name];
  if (!LucideIcon) return null;
  return <LucideIcon size={size} style={style} className={className} strokeWidth={1.75} />;
}
